name: mac test

on: 
  push:
    tags:
      - test[0-9]+

permissions: read-all

jobs:
  build:
    name: test
    runs-on: macos-13
    steps:
      - name: List Xcode installations
        run: ls /Applications | grep "Xcode"

      - name: Switch Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v
